# Generated by Django 2.2.16 on 2023-01-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230128_2127'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique follower'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
